__author__ = "Kristina Song"
__email__ = "kristina.song@usherbrooke.ca"


import os
import glob
import pandas as pd


##### store paths and user-specific variables #####
configfile: "config/config.yaml"


#### load snoRNA and RBP list ####
sno_list = pd.read_table(config["path"]["snoRNA_list"]).gene_id.values.tolist()
rbp_list = pd.read_table(config["path"]["RBP_list"]).gene_name.values.tolist()


#############################
## Load rules
#############################

include: "rules/filter.smk"
include: "rules/interactions.smk"
include: "rules/cytoscape.smk"


#############################
## Target rules
#############################

rule all:
    input:
        # Generate snoRNA and RBP interactions
        RBP_interactions = expand("results/interactions/ENCODE/{rbp}.bed", rbp=rbp_list),
        sno_interactions = expand("results/interactions/snoGloBe_HTRRI/{sno}.bed", sno=sno_list),
        STRING = "results/interactions/STRING/physical_RBP_RBP.tsv",
        sno_RBP_target_overlap = "results/interactions/sno_RBP_target_overlap/bh_sno_RBP_overlap.tsv",
        RBP_binds_to_sno = "results/interactions/RBP_binds_to_sno/all_RBP_binding_to_sno.tsv",
        network_data = expand("results/networks/{type}.tsv", type=['nodes','edges','RBP_function_localization','snoRNA_targets']),
        # Build network on Cytoscape app
        network = "results/networks/snoFlake.cys" # CYTOSCAPE HAS TO BE OPEN
