---
path:
  fasta: resources/Homo_sapiens.GRCh38.110.dna.primary_assembly.fa
  genome: resources/Homo_sapiens.GRCh38.110.dna.primary_assembly.genome
  ENCODE: resources/ENCODE_RBP_2023/
  snoglobe: resources/snoglobe_predictions_2024/
  STRING_interactions: resources/STRING_v12/9606.protein.physical.links.v12.0.txt.gz
  STRING_info: resources/STRING_v12/9606.protein.info.v12.0.txt.gz
  HTRRI: resources/htrri_duplexdiscoverer_dgs.tsv
  snoRNA_list: resources/filtered_genes_CD/sig_exp_CD_snoRNAs.tsv
  RBP_list: resources/filtered_genes_CD/exp_RBPs.tsv
  pc_list: resources/filtered_genes_CD/exp_pc_genes.tsv
  snoDB: resources/snoDB_All_V2.0.tsv
  rRNA_targets: resources/snoDB_rRNA_interactions.tsv
  snRNA_targets: resources/SNORD_snRNA_targets.tsv
  ENCORE: resources/ENCORE_overview_table_2024-10-06.csv
  gtf: resources/Homo_sapiens.GRCh38.110_snoRNAs_tRNAs.gtf

thresholds:
  ENCODE: 3
  snoGloBe: 0.98
  HTRRI: 5
  STRING: 900
  sno_RBP_overlap_fdr: 0.001
